# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dotpoint pathology
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pathology" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: none

# Build settings
markdown: kramdown

exclude: [vendor]

gems:
  - algoliasearch-jekyll
  
algolia:
  application_id: 'FQW1P6XHX4'
  index_name:     'dotpoint'
  record_css_selector: 'p,ul'
  excluded_files:
    - index.html
    - thyroid.html
